<a href="https://colab.research.google.com/github/derektorquette/estatistica-para-analise-de-dados-com-python/blob/main/amostragens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **AMOSTRAGENS**

In [ ]:
from google.colab import drive # o dataset foi utilizado no googledrive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np # matemática
import pandas as pd # manipulação de dados

In [ ]:
enem_sp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Estatística para Análise de Dados com Python/enem_2019_tratado.csv',
                      sep=',', encoding='iso-8859-1') # por padrão o python salva com vírgula

In [ ]:
enem_sp.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,NaN,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,15567761.0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
2,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,35904958.0,...,393.2,Espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
3,"1,90E+11",Embu-Guaçu,17,F,1,parda,1,2,pública,NaN,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
4,"1,90E+11",Guarulhos,23,F,1,branca,1,1,não_respondeu,NaN,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim

In [ ]:
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas'] # comando para localizar a cidade

In [ ]:
enem_campinas.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
15,"1,90E+11",Campinas,17,F,1,branca,1,1,não_respondeu,NaN,...,496.5,Inglês,1.0,160.0,120.0,140.0,140.0,120.0,680.0,Sim
31,"1,90E+11",Campinas,19,F,1,parda,1,1,não_respondeu,NaN,...,73.1,Inglês,1.0,140.0,120.0,160.0,140.0,160.0,720.0,Sim
51,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
169,"1,90E+11",Campinas,17,M,1,branca,1,2,privada,NaN,...,624.4,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim

In [ ]:
enem_campinas.shape

(13198, 28)

## **AMOSTRAGEM ALEATÓRIA SIMPLES** - Seleção executada por meio de sorteio, sem nenhum filtro.

In [ ]:
np.random.seed(1) # valor aleatórios

In [ ]:
amos_simples = enem_campinas.sample(frac=0.20) # Porcentagem aleatória dentro de campinas, neste caso 20 porcento

In [ ]:
amos_simples.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
327999,"1,90E+11",Campinas,20,M,1,preta,1,1,não_respondeu,NaN,...,459.6,Inglês,1.0,180.0,200.0,180.0,200.0,200.0,960.0,Sim
235222,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018296.0,...,48.8,Inglês,1.0,160.0,180.0,160.0,140.0,140.0,780.0,Sim
134221,"1,90E+11",Campinas,18,F,1,parda,1,2,pública,NaN,...,429.9,Inglês,1.0,100.0,120.0,100.0,80.0,100.0,500.0,Sim
358407,"1,90E+11",Campinas,25,M,0,parda,1,1,não_respondeu,NaN,...,687.4,Espanhol,1.0,140.0,120.0,120.0,140.0,140.0,660.0,Não
173364,"1,90E+11",Campinas,18,M,1,parda,1,1,não_respondeu,NaN,...,617.9,Inglês,1.0,140.0,120.0,140.0,140.0,80.0,620.0,Sim

In [ ]:
amos_simples = enem_campinas.sample(3000) # Quantidade numérica - selecionando 3000 registros

In [ ]:
amos_simples.shape

(3000, 28)

**OUTRA MANEIRA DE FAZER UMA AMOSTRAGEM SIMPLES**

In [ ]:
np.random.seed(2)

In [ ]:
amostra = np.random.choice(a=[0,1], size=13198, replace=True, p=[0.8, 0.2])

In [ ]:
amostra

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
len(amostra[amostra == 0]) # 80%

10566

In [ ]:
len(amostra[amostra == 1]) # 20%

2632

In [ ]:
amos_simples = enem_campinas.loc[amostra == 1] # Localizar quem é 1

In [ ]:
amos_simples.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
949,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35924573.0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
1058,"1,90E+11",Campinas,19,M,1,parda,1,1,não_respondeu,NaN,...,474.6,Inglês,1.0,120.0,120.0,120.0,160.0,100.0,620.0,Sim
1980,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35018302.0,...,479.9,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Não
2053,"1,90E+11",Campinas,18,F,1,parda,1,1,não_respondeu,NaN,...,424.2,Inglês,1.0,100.0,40.0,20.0,80.0,0.0,240.0,Sim
2328,"1,90E+11",Campinas,20,F,1,parda,2,1,não_respondeu,NaN,...,552.5,Espanhol,1.0,120.0,120.0,100.0,100.0,80.0,520.0,Sim

## **AMOSTRAGEM SISTEMÁTICA** - Membros da população são ordenados numericamente e são selecionados aleatoriamente obedecendo uma sequência numérica. (Ex.: crição de números para cada amostra e seleção obedecendo uma ordem numérica).

In [ ]:
enem_campinas.shape

(13198, 28)

In [ ]:
np.random.seed(2) # semente para fixar a escolha aleatória
inicio = np.random.choice(10, 1) # limite do número e a quantidade de numero

In [ ]:
inicio # na escolha de um número de 0 a 10, foi escolhido o 8

array([8])

In [ ]:
amostra2 = np.arange(inicio,13198,100) # valor inicial, valor total e valor da contagem em sequência
amostra2

/tmp/ipykernel_9817/1749086747.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  amostra2 = np.arange(inicio,13198,100) # valor inicial, valor total e valor da contagem em sequência

array([    8,   108,   208,   308,   408,   508,   608,   708,   808,
         908,  1008,  1108,  1208,  1308,  1408,  1508,  1608,  1708,
        1808,  1908,  2008,  2108,  2208,  2308,  2408,  2508,  2608,
        2708,  2808,  2908,  3008,  3108,  3208,  3308,  3408,  3508,
        3608,  3708,  3808,  3908,  4008,  4108,  4208,  4308,  4408,
        4508,  4608,  4708,  4808,  4908,  5008,  5108,  5208,  5308,
        5408,  5508,  5608,  5708,  5808,  5908,  6008,  6108,  6208,
        6308,  6408,  6508,  6608,  6708,  6808,  6908,  7008,  7108,
        7208,  7308,  7408,  7508,  7608,  7708,  7808,  7908,  8008,
        8108,  8208,  8308,  8408,  8508,  8608,  8708,  8808,  8908,
        9008,  9108,  9208,  9308,  9408,  9508,  9608,  9708,  9808,
        9908, 10008, 10108, 10208, 10308, 10408, 10508, 10608, 10708,
       10808, 10908, 11008, 11108, 11208, 11308, 11408, 11508, 11608,
       11708, 11808, 11908, 12008, 12108, 12208, 12308, 12408, 12508,
       12608, 12708, 12808, 12908, 13008, 13108])

In [ ]:
amos_sistematica = enem_campinas.iloc[amostra2,:]

In [ ]:
amos_sistematica

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
401,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
5079,"1,90E+11",Campinas,18,F,1,branca,1,2,pública,35018855.0,...,419.9,Inglês,1.0,140.0,120.0,120.0,120.0,140.0,640.0,Sim
9218,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,617.1,Inglês,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
13685,"1,90E+11",Campinas,20,M,1,parda,1,1,não_respondeu,NaN,...,576.4,Inglês,1.0,160.0,200.0,180.0,200.0,180.0,920.0,Sim
18239,"1,90E+11",Campinas,20,M,1,branca,1,1,não_respondeu,NaN,...,796.2,Inglês,1.0,160.0,200.0,200.0,200.0,200.0,960.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481894,"1,90E+11",Campinas,34,M,1,parda,1,1,não_respondeu,NaN,...,932.1,Inglês,1.0,140.0,120.0,160.0,160.0,160.0,740.0,Sim
485805,"1,90E+11",Campinas,16,F,1,branca,1,2,pública,35039901.0,...,441.6,Inglês,1.0,120.0,120.0,100.0,120.0,0.0,460.0,Sim
488958,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,492.9,Inglês,1.0,160.0,120.0,140.0,120.0,140.0,680.0,Sim
492626,"1,90E+11",Campinas,21,M,1,branca,1,1,não_respondeu,NaN,...,51.1,Inglês,1.0,120.0,120.0,120.0,100.0,0.0,460.0,Sim
496410,"1,90E+11",Campinas,19,M,1,preta,1,1,não_respondeu,NaN,...,404.4,Inglês,1.0,100.0,80.0,80.0,80.0,40.0,380.0,Sim

**OUTRA MANEIRA**

In [ ]:
np.random.seed(30)

In [ ]:
inicio = np.random.choice(10, 1)
passo = np.random.randint(100, 150, 1)

In [ ]:
inicio

array([5])

In [ ]:
passo

array([137])

In [ ]:
amostra2 = np.arange(inicio,13198,passo)
amostra2

/tmp/ipykernel_9817/2764270883.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  amostra2 = np.arange(inicio,13198,passo)

array([    5,   142,   279,   416,   553,   690,   827,   964,  1101,
        1238,  1375,  1512,  1649,  1786,  1923,  2060,  2197,  2334,
        2471,  2608,  2745,  2882,  3019,  3156,  3293,  3430,  3567,
        3704,  3841,  3978,  4115,  4252,  4389,  4526,  4663,  4800,
        4937,  5074,  5211,  5348,  5485,  5622,  5759,  5896,  6033,
        6170,  6307,  6444,  6581,  6718,  6855,  6992,  7129,  7266,
        7403,  7540,  7677,  7814,  7951,  8088,  8225,  8362,  8499,
        8636,  8773,  8910,  9047,  9184,  9321,  9458,  9595,  9732,
        9869, 10006, 10143, 10280, 10417, 10554, 10691, 10828, 10965,
       11102, 11239, 11376, 11513, 11650, 11787, 11924, 12061, 12198,
       12335, 12472, 12609, 12746, 12883, 13020, 13157])

In [ ]:
amostra2_camp = enem_campinas.iloc[amostra2,:] #todas as colunas

In [ ]:
amostra2_camp.shape

(97, 28)

## **AMOSTRAGEM ESTRATIFICADA** - Divisão da população em grupos e seleção aleatória de uma amostra de cada grupo. (Ex: divisão por reigião, classe social, religião, etc.)

In [ ]:
enem_campinas['RACA'].value_counts() # contagem

RACA
branca           7507
parda            3652
preta            1510
amarela           279
nao_declarado     205
indígena           45
Name: count, dtype: int64

In [ ]:
enem_campinas['TP_LINGUA'].value_counts() # contagem

TP_LINGUA
Inglês      9843
Espanhol    3355
Name: count, dtype: int64

**Para quantidade pequena de grupos** - amostragem simples e aleatória

- lembrando que esse conceito de 'raça' é retirado do IBGE, essa classificação gera controvérsias

In [ ]:
branca = enem_campinas.loc[enem_campinas.RACA == 'branca'].sample(frac=0.10) # fração de 10% na coluna 'Raça'
branca.shape # quantidade

(751, 28)

(751, 28)

In [ ]:
parda = enem_campinas.loc[enem_campinas.RACA == 'parda'].sample(frac=0.10)
parda.shape

(365, 28)

In [ ]:
preta = enem_campinas.loc[enem_campinas.RACA == 'preta'].sample(frac=0.10)
preta.shape

(151, 28)

In [ ]:
amarela = enem_campinas.loc[enem_campinas.RACA == 'amarela'].sample(frac=0.10)
amarela.shape

(28, 28)

In [ ]:
nd = enem_campinas.loc[enem_campinas.RACA == 'nao_declarado'].sample(frac=0.10)
nd.shape

(20, 28)

In [ ]:
indigena = enem_campinas.loc[enem_campinas.RACA == 'indígena'].sample(frac=0.10)
indigena.shape

(4, 28)

In [ ]:
indigena.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
234173,"1,90E+11",Campinas,18,F,1,indígena,1,1,não_respondeu,NaN,...,505.9,Espanhol,1.0,120.0,160.0,120.0,120.0,100.0,620.0,Não
94148,"1,90E+11",Campinas,17,F,1,indígena,1,2,pública,35039901.0,...,380.8,Espanhol,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
88722,"1,90E+11",Campinas,18,F,1,indígena,1,2,privada,35112884.0,...,574.2,Espanhol,1.0,120.0,40.0,40.0,160.0,40.0,400.0,Sim
189875,"1,90E+11",Campinas,27,F,1,indígena,1,1,não_respondeu,NaN,...,403.2,Inglês,1.0,120.0,40.0,40.0,100.0,60.0,360.0,Sim

In [ ]:
amos_estra = pd.concat([branca, parda, preta, amarela, nd, indigena]) # concatenação em uma única tabela em outra variável

In [ ]:
amos_estra

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
154181,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,598.8,Inglês,1.0,140.0,120.0,100.0,180.0,100.0,640.0,Sim
366239,"1,90E+11",Campinas,24,F,1,branca,1,1,não_respondeu,NaN,...,589.2,Inglês,1.0,140.0,120.0,120.0,120.0,120.0,620.0,Sim
116461,"1,90E+11",Campinas,17,F,1,branca,1,2,privada,NaN,...,50.8,Inglês,1.0,120.0,140.0,120.0,120.0,120.0,620.0,Sim
248333,"1,90E+11",Campinas,19,M,1,branca,1,1,não_respondeu,NaN,...,836.3,Inglês,1.0,160.0,140.0,160.0,200.0,180.0,840.0,Sim
299044,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,481.6,Inglês,1.0,80.0,120.0,100.0,120.0,0.0,420.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259008,"1,90E+11",Campinas,23,M,1,nao_declarado,1,1,não_respondeu,NaN,...,516.7,Inglês,1.0,80.0,100.0,100.0,80.0,100.0,460.0,Sim
234173,"1,90E+11",Campinas,18,F,1,indígena,1,1,não_respondeu,NaN,...,505.9,Espanhol,1.0,120.0,160.0,120.0,120.0,100.0,620.0,Não
94148,"1,90E+11",Campinas,17,F,1,indígena,1,2,pública,35039901.0,...,380.8,Espanhol,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
88722,"1,90E+11",Campinas,18,F,1,indígena,1,2,privada,35112884.0,...,574.2,Espanhol,1.0,120.0,40.0,40.0,160.0,40.0,400.0,Sim
189875,"1,90E+11",Campinas,27,F,1,indígena,1,1,não_respondeu,NaN,...,403.2,Inglês,1.0,120.0,40.0,40.0,100.0,60.0,360.0,Sim

**Grandes quantidades de grupos** - método de machine/deep learning

In [ ]:
from sklearn.model_selection import train_test_split # usando treino de teste

In [ ]:
X_treino, X_teste, y_treino, amos_estra = train_test_split(enem_campinas.drop('RACA',axis=1),enem_campinas['RACA'], # axis é eixo, coluna é 1, linha é zero
                                                    stratify=enem_campinas['RACA'], test_size=0.20)

In [ ]:
amos_estra.shape

(2640,)

In [ ]:
amos_estra.value_counts()

RACA
branca           1502
parda             730
preta             302
amarela            56
nao_declarado      41
indígena            9
Name: count, dtype: int64

In [ ]:
list(amos_estra)

[283554,
 57002,
 399102,
 399707,
 13281,
 296100,
 483325,
 408622,
 203540,
 123049,
 451418,
 106727,
 492826,
 95395,
 80350,
 377705,
 85657,
 268745,
 227896,
 254688,
 394668,
 68073,
 410027,
 244410,
 108202,
 113894,
 148669,
 184635,
 346855,
 32746,
 157728,
 401170,
 355284,
 431712,
 201400,
 375806,
 333813,
 183053,
 209618,
 252548,
 68274,
 288713,
 304728,
 455378,
 476289,
 213216,
 367194,
 43730,
 396041,
 278639,
 179675,
 249726,
 152919,
 1690,
 275677,
 264324,
 367713,
 306861,
 221487,
 381828,
 288607,
 279831,
 469811,
 41055,
 438278,
 46335,
 243765,
 118271,
 289042,
 13162,
 325628,
 190963,
 435053,
 136845,
 281011,
 183261,
 415243,
 403412,
 469669,
 162150,
 168858,
 319808,
 428561,
 62631,
 324252,
 227561,
 6748,
 146321,
 195187,
 494014,
 121467,
 239174,
 42520,
 301359,
 28607,
 338310,
 147887,
 183177,
 481287,
 69150,
 89120,
 252050,
 339045,
 212885,
 446208,
 286049,
 367280,
 498555,
 6727,
 226846,
 497956,
 312914,
 158966,
 54250,
 260244,
 350563,
 281791,
 252547,
 456738,
 451400,
 319496,
 237015,
 351723,
 100657,
 374678,
 380344,
 114980,
 72132,
 356149,
 304843,
 402125,
 125251,
 407341,
 406024,
 174035,
 176982,
 64277,
 294310,
 235862,
 402980,
 282220,
 179233,
 286136,
 72361,
 348333,
 157575,
 435595,
 40304,
 264112,
 413519,
 218116,
 45568,
 208693,
 290328,
 477158,
 76885,
 29987,
 80851,
 386195,
 215945,
 366392,
 232253,
 496040,
 367039,
 414868,
 350084,
 118125,
 408624,
 69567,
 381718,
 320730,
 255334,
 49340,
 140991,
 263356,
 311795,
 442830,
 472100,
 399161,
 149037,
 400806,
 33030,
 480818,
 454923,
 116710,
 275982,
 2538,
 404756,
 201390,
 125641,
 79774,
 233071,
 301162,
 70857,
 54114,
 268055,
 305169,
 379848,
 19287,
 471128,
 393315,
 336245,
 150727,
 220386,
 410439,
 359250,
 437437,
 60255,
 183009,
 489383,
 26985,
 29913,
 396937,
 322850,
 56131,
 274848,
 496515,
 351661,
 88913,
 300502,
 469768,
 274628,
 422867,
 443863,
 133128,
 201142,
 358689,
 350431,
 145982,
 183855,
 160002,
 490173,
 43460,
 288420,
 352653,
 152125,
 191519,
 44157,
 248297,
 107753,
 395400,
 189662,
 408879,
 193973,
 307318,
 396699,
 387132,
 425119,
 136071,
 229735,
 344359,
 195447,
 445819,
 411274,
 104915,
 155279,
 75611,
 199307,
 224104,
 447346,
 126402,
 472594,
 381539,
 478816,
 330702,
 461752,
 180536,
 57754,
 36994,
 288522,
 204794,
 18856,
 16529,
 409667,
 439842,
 18064,
 285665,
 41690,
 198534,
 20422,
 429600,
 474515,
 168835,
 74098,
 203950,
 297613,
 2126,
 438200,
 301232,
 229959,
 215006,
 435944,
 385054,
 481365,
 446609,
 171788,
 325446,
 348395,
 184213,
 196390,
 49726,
 416357,
 207436,
 252554,
 397270,
 1058,
 180267,
 87675,
 8046,
 297513,
 344547,
 450473,
 226709,
 105303,
 138663,
 420768,
 276672,
 209571,
 460156,
 218644,
 28944,
 223627,
 149682,
 410359,
 455256,
 40815,
 284814,
 165468,
 74571,
 198434,
 161676,
 422491,
 200785,
 139905,
 378249,
 449454,
 390715,
 458217,
 66744,
 277429,
 95041,
 324307,
 98715,
 390511,
 441408,
 420380,
 87717,
 154233,
 320195,
 435578,
 318310,
 368940,
 461122,
 341691,
 293118,
 268185,
 248983,
 452853,
 42862,
 431688,
 83769,
 314061,
 68809,
 72085,
 260946,
 128827,
 8417,
 92419,
 452317,
 275480,
 339978,
 298903,
 398631,
 377354,
 423638,
 451725,
 192630,
 166304,
 115455,
 38720,
 154643,
 175566,
 270524,
 296143,
 280159,
 396559,
 270458,
 214228,
 396198,
 70182,
 329613,
 417298,
 227146,
 285563,
 57429,
 141246,
 461257,
 409265,
 305839,
 227292,
 401234,
 484784,
 213726,
 189764,
 186690,
 145948,
 450265,
 156066,
 470573,
 179914,
 130243,
 478375,
 288423,
 339546,
 120768,
 438792,
 202237,
 30445,
 395109,
 361853,
 300724,
 23029,
 128008,
 488297,
 434620,
 420777,
 255600,
 132396,
 469606,
 273766,
 435499,
 223863,
 186,
 60090,
 417381,
 52088,
 167043,
 347543,
 44773,
 398578,
 16099,
 183312,
 487162,
 225866,
 359026,
 192585,
 493707,
 184836,
 445898,
 332792,
 133622,
 382414,
 102766,
 186334,
 246073,
 92690,
 243795,
 140389,
 496965,
 470652,
 301032,
 368386,
 470390,
 80720,
 20916,
 487602,
 403458,
 130510,
 353700,
 111355,
 337722,
 139579,
 344466,
 298716,
 382113,
 156658,
 159977,
 330439,
 416275,
 43170,
 114407,
 285696,
 328994,
 374911,
 39756,
 391623,
 175535,
 437342,
 106130,
 18397,
 334247,
 399097,
 65644,
 471026,
 236837,
 359925,
 391790,
 445902,
 189604,
 473166,
 201911,
 370593,
 42305,
 136828,
 288115,
 213246,
 418527,
 402238,
 190437,
 440800,
 496143,
 265870,
 490807,
 12876,
 27205,
 224757,
 181458,
 494733,
 134816,
 481894,
 328902,
 267178,
 479934,
 245366,
 70436,
 288932,
 215008,
 30351,
 277490,
 407737,
 7601,
 307913,
 329205,
 150127,
 426578,
 447393,
 239419,
 179998,
 484306,
 368462,
 400764,
 1376,
 412741,
 128716,
 462153,
 401607,
 349853,
 371916,
 101631,
 66446,
 226088,
 43933,
 497331,
 356009,
 266805,
 446242,
 312632,
 253690,
 289388,
 374404,
 452919,
 186905,
 287839,
 265297,
 150666,
 436766,
 188712,
 341246,
 188641,
 247914,
 42580,
 107765,
 107196,
 311704,
 78579,
 195479,
 319260,
 331467,
 481981,
 450385,
 324289,
 199312,
 270707,
 245350,
 294614,
 497539,
 492104,
 220625,
 364319,
 393950,
 218574,
 496733,
 442602,
 39580,
 209771,
 411314,
 249755,
 217165,
 59099,
 356484,
 467280,
 82873,
 434782,
 233283,
 328898,
 326462,
 249401,
 31520,
 491632,
 475272,
 60579,
 145634,
 460967,
 36707,
 381550,
 261142,
 340275,
 280655,
 292483,
 415471,
 242024,
 262332,
 382397,
 496935,
 127562,
 406707,
 263851,
 490126,
 366868,
 187602,
 142369,
 204616,
 282557,
 202293,
 245913,
 262008,
 91746,
 98018,
 249016,
 144385,
 247616,
 294006,
 43748,
 291774,
 224040,
 481445,
 335893,
 491372,
 62217,
 3744,
 434311,
 396961,
 12193,
 469922,
 177775,
 255668,
 223993,
 476559,
 404917,
 300367,
 299791,
 324269,
 260042,
 395870,
 208556,
 200967,
 18170,
 244731,
 47701,
 88714,
 239716,
 43572,
 22137,
 403306,
 461471,
 432680,
 357573,
 350478,
 36072,
 279746,
 272345,
 393672,
 336957,
 1691,
 301499,
 80527,
 370768,
 299991,
 442467,
 227015,
 212559,
 400463,
 189967,
 211755,
 295071,
 177481,
 299980,
 444668,
 19510,
 210698,
 228878,
 321915,
 396969,
 144427,
 472964,
 3350,
 68420,
 198459,
 213325,
 83130,
 305539,
 233342,
 311671,
 218478,
 282625,
 41570,
 455964,
 416008,
 328232,
 472178,
 229803,
 311629,
 49073,
 159295,
 418413,
 285739,
 404230,
 133376,
 306132,
 134140,
 259931,
 225305,
 86553,
 10495,
 165782,
 309843,
 337534,
 277290,
 429244,
 401826,
 38274,
 314675,
 342733,
 280318,
 424291,
 498878,
 52956,
 348435,
 163985,
 379326,
 220177,
 427322,
 361818,
 492986,
 454121,
 322523,
 91204,
 495000,
 456510,
 355990,
 345428,
 68622,
 488798,
 246494,
 325653,
 120084,
 28057,
 121706,
 64417,
 113305,
 291258,
 278162,
 450932,
 22734,
 1267,
 344578,
 165281,
 413135,
 53977,
 165736,
 488340,
 115957,
 189997,
 351303,
 105154,
 306815,
 351166,
 353144,
 250204,
 348796,
 228093,
 276628,
 357319,
 329697,
 347320,
 429819,
 130234,
 194168,
 67196,
 124102,
 253872,
 381023,
 321470,
 440136,
 242829,
 368185,
 386077,
 13673,
 480433,
 455821,
 280245,
 131580,
 254966,
 342033,
 190024,
 299290,
 106948,
 390886,
 33482,
 495391,
 327292,
 343434,
 386366,
 129863,
 309034,
 364927,
 459692,
 347037,
 94696,
 347574,
 29499,
 236534,
 271054,
 483042,
 112099,
 136765,
 468534,
 111131,
 479793,
 499869,
 293181,
 303056,
 378980,
 125455,
 343774,
 107110,
 379736,
 92902,
 353566,
 295057,
 59948,
 421394,
 67809,
 374787,
 230520,
 375527,
 228999,
 479534,
 261048,
 164297,
 451836,
 138929,
 417192,
 222980,
 376973,
 13342,
 274141,
 448074,
 112606,
 330036,
 371747,
 364530,
 385739,
 68927,
 49045,
 25862,
 16106,
 220870,
 183318,
 27875,
 388860,
 335311,
 369840,
 36877,
 292122,
 377534,
 177752,
 228437,
 355549,
 412550,
 1631,
 195688,
 169775,
 144257,
 44117,
 140286,
 208362,
 261740,
 298474,
 201574,
 368046,
 235423,
 435468,
 467740,
 202789,
 165728,
 281345,
 197852,
 1852,
 287349,
 189733,
 65870,
 244361,
 352276,
 485201,
 421430,
 303808,
 25195,
 338798,
 118714,
 490848,
 408557,
 463266,
 438277,
 67604,
 74138,
 82830,
 169169,
 171968,
 102603,
 231914,
 276661,
 423932,
 437625,
 130269,
 183506,
 231517,
 64841,
 295144,
 219557,
 237131,
 428379,
 334585,
 351163,
 495488,
 205629,
 356186,
 7869,
 262850,
 77324,
 321288,
 14147,
 345406,
 484107,
 346125,
 251545,
 431424,
 56306,
 349878,
 411742,
 371093,
 47930,
 272913,
 101936,
 429534,
 178579,
 397839,
 212234,
 37776,
 254052,
 124109,
 361855,
 321040,
 485218,
 83019,
 463767,
 469040,
 244519,
 25390,
 42313,
 291768,
 228393,
 177930,
 310543,
 333481,
 59836,
 476975,
 30193,
 192123,
 296930,
 188351,
 8223,
 307791,
 419116,
 334092,
 221481,
 215828,
 271170,
 46100,
 489336,
 ...]

In [ ]:
amos_estra

Index([283554,  57002, 399102, 399707,  13281, 296100, 483325, 408622, 203540,
       123049,
       ...
       382483,  88686, 213610, 412602, 425419, 327551, 268978, 350672, 263103,
       206322],
      dtype='int64', length=2640)

In [ ]:
amos_estra_camp = enem_campinas.loc[amos_estra,:] # transformando o vetor em tabela

In [ ]:
amos_estra_camp

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
283554,"1,90E+11",Campinas,22,F,1,branca,2,1,não_respondeu,NaN,...,486.2,Espanhol,1.0,100.0,80.0,60.0,100.0,40.0,380.0,Sim
57002,"1,90E+11",Campinas,18,F,1,preta,1,1,não_respondeu,NaN,...,612.5,Inglês,1.0,120.0,160.0,120.0,160.0,160.0,720.0,Sim
399102,"1,90E+11",Campinas,25,M,1,branca,1,1,não_respondeu,NaN,...,619.2,Espanhol,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
399707,"1,90E+11",Campinas,17,F,1,branca,1,2,privada,NaN,...,680.3,Inglês,1.0,160.0,120.0,140.0,160.0,120.0,700.0,Sim
13281,"1,90E+11",Campinas,21,F,1,branca,1,1,não_respondeu,NaN,...,413.6,Inglês,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327551,"1,90E+11",Campinas,17,M,1,parda,1,2,privada,35118084.0,...,800.6,Inglês,1.0,160.0,180.0,160.0,200.0,160.0,860.0,Sim
268978,"1,90E+11",Campinas,21,F,1,branca,1,1,não_respondeu,NaN,...,492.3,Inglês,1.0,120.0,120.0,140.0,140.0,100.0,620.0,Sim
350672,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018806.0,...,53.5,Espanhol,1.0,140.0,40.0,40.0,80.0,0.0,300.0,Sim
263103,"1,90E+11",Campinas,20,F,1,parda,1,1,não_respondeu,NaN,...,650.1,Inglês,1.0,160.0,120.0,120.0,120.0,140.0,660.0,Sim
206322,"1,90E+11",Campinas,18,F,1,branca,1,2,pública,35924573.0,...,514.2,Espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim

## **AMOSTRAGEM POR CONGLOMERADO (AGRUPAMENTO)** - Divisão da população em grupos com características similares, porém heterogêneas, e seleção aleatória de alguns grupos para analisar todos os elemenetos destes grupos. (Ex.: Divisão da população de escolas estaduais por região)

In [ ]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'pública']

In [ ]:
escolas_publicas.shape

(4175, 28)

In [ ]:
escolas_publicas

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
51,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
325,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35907376.0,...,509.3,Inglês,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
949,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35924573.0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
1004,"1,90E+11",Campinas,24,F,1,branca,1,2,pública,35980158.0,...,359.8,Espanhol,1.0,120.0,40.0,100.0,100.0,60.0,420.0,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499530,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35042651.0,...,491.6,Inglês,1.0,140.0,120.0,120.0,160.0,120.0,660.0,Sim
499640,"1,90E+11",Campinas,22,M,1,preta,1,2,pública,35018533.0,...,365.4,Espanhol,1.0,80.0,60.0,60.0,80.0,0.0,280.0,Sim
499691,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,35018089.0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim
499749,"1,90E+11",Campinas,17,M,1,branca,1,2,pública,35040400.0,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
499862,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018879.0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim

In [ ]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts() #separando em grupos das escolas públicas
amostras

CO_ESCOLA
35045937.0    152
35018363.0    134
35018797.0    124
35018879.0    110
35018326.0    109
             ...
35009751.0      1
35500012.0      1
35462342.0      1
35985600.0      1
35047053.0      1
Name: count, Length: 186, dtype: int64

In [ ]:
amostras.index

Index([35045937.0, 35018363.0, 35018797.0, 35018879.0, 35018326.0, 35047200.0,
       35901097.0, 35045949.0, 35018235.0, 35018302.0,
       ...
       35112689.0, 35337833.0, 35015830.0, 35159943.0, 35924672.0, 35009751.0,
       35500012.0, 35462342.0, 35985600.0, 35047053.0],
      dtype='float64', name='CO_ESCOLA', length=186)

In [ ]:
amostragem = np.random.choice(a=[0,1],size=186, replace=True, p=[0.85, 0.15]) #criar uma amostragem

In [ ]:
amostragem

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
amos_conglomerado = amostras.loc[amostragem == 1]

In [ ]:
amos_conglomerado

CO_ESCOLA
35018235.0    75
35045718.0    67
35045664.0    60
35018569.0    55
35047120.0    49
35018806.0    35
35018491.0    31
35812900.0    26
35903875.0    25
35467765.0    23
35045676.0    23
35018211.0    22
35018715.0    21
35039895.0    20
35040400.0    18
35037965.0    13
35907406.0    12
35112884.0     9
35065535.0     9
35924933.0     8
35018478.0     8
35437153.0     7
35907397.0     7
35018867.0     6
35045585.0     6
35579403.0     3
35458569.0     2
23128178.0     1
35112926.0     1
35058836.0     1
35445757.0     1
35042523.0     1
35045962.0     1
35337833.0     1
Name: count, dtype: int64

In [ ]:
amos_conglomerado.shape

(34,)

In [ ]:
amos_conglomerado.index

Index([35018235.0, 35045718.0, 35045664.0, 35018569.0, 35047120.0, 35018806.0,
       35018491.0, 35812900.0, 35903875.0, 35467765.0, 35045676.0, 35018211.0,
       35018715.0, 35039895.0, 35040400.0, 35037965.0, 35907406.0, 35112884.0,
       35065535.0, 35924933.0, 35018478.0, 35437153.0, 35907397.0, 35018867.0,
       35045585.0, 35579403.0, 35458569.0, 23128178.0, 35112926.0, 35058836.0,
       35445757.0, 35042523.0, 35045962.0, 35337833.0],
      dtype='float64', name='CO_ESCOLA')

In [ ]:
amos_conglomerado = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin([35112859.0, 35905471.0, 35045950.0, 35018508.0, 35905461.0, #'isin' busca os códigos
              35914897.0, 35125568.0, 35127012.0, 35037965.0, 35018910.0,
              35127784.0, 35925962.0, 35907397.0, 35118084.0, 35579403.0,
              35458569.0, 35985296.0, 35045724.0, 35150095.0, 35138769.0,
              35337833.0, 35500012.0, 26127741.0, 35462342.0, 35445757.0,
              35058836.0, 35035956.0])]

In [ ]:
amos_conglomerado

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
2066,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35905471.0,...,598.8,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim
5050,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35045950.0,...,728.7,Inglês,1.0,140.0,160.0,140.0,140.0,140.0,720.0,Sim
5267,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35905461.0,...,416.5,Inglês,1.0,120.0,140.0,120.0,100.0,80.0,560.0,Sim
6279,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35907397.0,...,541.4,Espanhol,1.0,100.0,120.0,80.0,80.0,80.0,460.0,Sim
6389,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35112859.0,...,614.4,Inglês,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481186,"1,90E+11",Campinas,19,F,1,preta,1,2,pública,35905461.0,...,398.9,Espanhol,1.0,120.0,120.0,100.0,120.0,80.0,540.0,Sim
487155,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35905471.0,...,446.4,Inglês,1.0,120.0,120.0,120.0,120.0,0.0,480.0,Sim
491722,"1,90E+11",Campinas,17,M,1,preta,1,2,pública,35905471.0,...,431.5,Inglês,1.0,120.0,40.0,40.0,100.0,0.0,300.0,Sim
493548,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35018508.0,...,476.4,Inglês,1.0,160.0,140.0,120.0,160.0,120.0,700.0,Sim
499026,"1,90E+11",Campinas,17,M,2,parda,1,2,pública,35905471.0,...,388.9,Inglês,1.0,100.0,60.0,60.0,100.0,0.0,320.0,Sim