<a href="https://colab.research.google.com/github/derektorquette/estatistica-para-analise-de-dados-com-python/blob/main/5_estatistica_descritiva_medidas_centrais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ESTATÍSTICA DESCRITIVA - MEDIDAS DE TENDÊNCIA CENTRAL

In [1]:
import numpy as np
import pandas as pd

In [4]:
enem_sp = pd.read_csv('/content/enem_2019_tratado.csv',  # Fazendo upload do arquivo direto no drive
                      sep=',', encoding='iso-8859-1')

## Média

função mean()

In [5]:
enem_sp['IDADE'].mean()

np.float64(20.593387206464776)

In [9]:
enem_sp.IDADE.mean() # outra forma de fazer

np.float64(20.593387206464776)

In [11]:
round(enem_sp['IDADE'].mean(),2) # usa-se a função round para arredondar

np.float64(20.59)

In [17]:
enem_sp.NOTA_REDACAO.mean() # redação foi a maior média

np.float64(593.0183221986639)

In [18]:
enem_sp['NOTA_MT'].mean()

np.float64(497.5942403088371)

In [19]:
enem_sp.NOTA_CN.mean() # ciências naturais foi a menor média

np.float64(449.91700044005285)

In [20]:
enem_sp.NOTA_CH.mean()

np.float64(482.228053966476)

In [21]:
enem_sp.NOTA_LC.mean()

np.float64(491.94126215145815)

## Mediana

função median()

In [22]:
enem_sp['IDADE'].median()

18.0

In [23]:
enem_sp.NOTA_REDACAO.median()

600.0

In [24]:
enem_sp.NOTA_MT.median()

511.8

In [25]:
enem_sp.NOTA_CN.median()

478.1

In [26]:
enem_sp.NOTA_CH.median()

523.7

In [27]:
enem_sp['NOTA_LC'].median()

538.3

In [29]:
enem_sp.describe() # função resumo para descrição das variáveis

,IDADE,TP_ESTADO_CIVIL,TP_NACIONALIDADE,TP_ST_CONCLUSAO,CO_ESCOLA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO
count,499940.000000,499940.000000,499940.000000,499940.000000,1.768940e+05,499940.0,499940.0,499940.0,499940.0,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000,499940.000000
mean,20.593387,1.053206,1.029902,1.476085,3.521138e+07,1.0,1.0,1.0,1.0,449.917000,482.228054,491.941262,497.594240,1.072105,125.000760,127.066808,118.760691,124.989359,97.200704,593.018322
std,6.465291,0.380866,0.230986,0.510351,4.430392e+05,0.0,0.0,0.0,0.0,152.982255,161.122963,156.247134,183.465175,0.584314,28.629513,39.846083,36.778882,33.879299,57.787427,170.536724
min,12.000000,0.000000,0.000000,1.000000,1.100306e+07,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.000000,1.000000,1.000000,3.501625e+07,1.0,1.0,1.0,1.0,412.400000,450.600000,490.100000,427.900000,1.000000,120.000000,120.000000,100.000000,120.000000,60.000000,500.000000
50%,18.000000,1.000000,1.000000,1.000000,3.504496e+07,1.0,1.0,1.0,1.0,478.100000,523.700000,538.300000,511.800000,1.000000,120.000000,120.000000,120.000000,120.000000,100.000000,600.000000
75%,21.000000,1.000000,1.000000,2.000000,3.529070e+07,1.0,1.0,1.0,1.0,544.400000,578.100000,576.200000,617.900000,1.000000,140.000000,140.000000,140.000000,140.000000,140.000000,680.000000
max,91.000000,4.000000,4.000000,4.000000,5.300104e+07,1.0,1.0,1.0,1.0,860.900000,822.700000,772.300000,984.700000,9.000000,200.000000,200.000000,200.000000,200.000000,200.000000,1000.000000

In [30]:
round(enem_sp.describe(),1)

,IDADE,TP_ESTADO_CIVIL,TP_NACIONALIDADE,TP_ST_CONCLUSAO,CO_ESCOLA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO
count,499940.0,499940.0,499940.0,499940.0,176894.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0,499940.0
mean,20.6,1.1,1.0,1.5,35211378.2,1.0,1.0,1.0,1.0,449.9,482.2,491.9,497.6,1.1,125.0,127.1,118.8,125.0,97.2,593.0
std,6.5,0.4,0.2,0.5,443039.2,0.0,0.0,0.0,0.0,153.0,161.1,156.2,183.5,0.6,28.6,39.8,36.8,33.9,57.8,170.5
min,12.0,0.0,0.0,1.0,11003065.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,17.0,1.0,1.0,1.0,35016251.0,1.0,1.0,1.0,1.0,412.4,450.6,490.1,427.9,1.0,120.0,120.0,100.0,120.0,60.0,500.0
50%,18.0,1.0,1.0,1.0,35044957.0,1.0,1.0,1.0,1.0,478.1,523.7,538.3,511.8,1.0,120.0,120.0,120.0,120.0,100.0,600.0
75%,21.0,1.0,1.0,2.0,35290701.0,1.0,1.0,1.0,1.0,544.4,578.1,576.2,617.9,1.0,140.0,140.0,140.0,140.0,140.0,680.0
max,91.0,4.0,4.0,4.0,53001036.0,1.0,1.0,1.0,1.0,860.9,822.7,772.3,984.7,9.0,200.0,200.0,200.0,200.0,200.0,1000.0

## Moda

função mode()

In [31]:
enem_sp['IDADE'].mode()

0    17
Name: IDADE, dtype: int64

In [32]:
enem_sp.NOTA_REDACAO.mode()

0    600.0
Name: NOTA_REDACAO, dtype: float64

In [33]:
enem_sp.NOTA_MT.mode()

0    433.8
Name: NOTA_MT, dtype: float64

In [34]:
enem_sp.NOTA_CN.mode()

0    481.8
Name: NOTA_CN, dtype: float64

In [35]:
enem_sp.NOTA_CH.mode()

0    0.0
Name: NOTA_CH, dtype: float64

In [36]:
enem_sp.NOTA_LC.mode()

0    55.2
Name: NOTA_LC, dtype: float64

## Distribuição

### análise dos componentes de redação

In [37]:
enem_sp.COMP3.mode()

0    120.0
Name: COMP3, dtype: float64

In [38]:
enem_sp.COMP3.mean()

np.float64(118.76069128295396)

In [39]:
enem_sp.COMP3.median()

120.0

In [40]:
import plotly.express as px

In [41]:
grafico =  px.histogram (enem_sp,  x = "COMP3", nbins=15)
grafico.update_layout(width=400,height=400,title_text='Notas do componente 3 da redação - Enem SP 2019')
grafico.show()

In [42]:
enem_sp.COMP2.mode()

0    120.0
Name: COMP2, dtype: float64

In [43]:
enem_sp.COMP2.mean()

np.float64(127.06680801696204)

In [44]:
enem_sp.COMP2.median()

120.0

In [45]:
import plotly.express as px
grafico =  px.histogram (enem_sp,  x = "COMP2", nbins=15)
grafico.update_layout(width=400,height=400,title_text='Notas Componente 2: Redação - Enem SP 2019')
grafico.show()